//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedwoodPong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int PlayerRedScore { get; set; }
        public int PlayerBlueScore { get; set; }
        public int PlayerRedId { get; set; }
        public int PlayerBlueId { get; set; }
        public int WinningPlayerId { get; set; }
        public int LosingPlayerId { get; set; }
    
        public virtual Player PlayerRed { get; set; }
        public virtual Player PlayerBlue { get; set; }
        public virtual Player WinningPlayer { get; set; }
        public virtual Player LosingPlayer { get; set; }
    }
}
